version: '3.4'
services:
  mongodb:
    image: mongo:3.6
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
  postgres:
    image: postgres:10.1
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
